baseURL = 'https://killbeo-kingston.com'
title = 'Killbeo Kingston'
[params]
    description = "Site web de Killbeo Kingston. Une holding offrant des services de travaux et rénovation, de conciergerie, ainsi que de conseil et gestion d'entreprise."
    favicon = "/img/logo1.png"
    logo = "/img/logo1.png"
    
[menu]
[[menu.main]]
    name = "A propos" 
    url = "/apropos" 
    weight = 2

[[menu.main]]
    name = "Contact" 
    url = "/contact" 
    weight = 3
